name: golangci-lint Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yml
      - .ci/.golangci*.yml
      - .ci/tools/**
      - internal/**
      - go.sum
      - main.go
      - names/**
      - tools/**

jobs:
  golangci-linta:
    name: 1 of 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci.yml
  golangci-lintb:
    name: 2 of 2
    needs: [golangci-linta]
    runs-on: [custom, linux, xl]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci2.yml
