name: tfsdk2fw Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - internal/generate/common/**
      - internal/provider/**
      - tools/tfsdk2fw/**

jobs:
  tfsdk2fw_go_mod:
    name: go mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version-file: tools/tfsdk2fw/go.mod
      - name: go mod
        run: |
          cd tools/tfsdk2fw/
          echo "==> Checking tfsdk2fw with go mod tidy..."
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo; echo "Unexpected difference in tools/tfsdk2fw/go.mod or tools/tfsdk2fw/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
